/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.matriz;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Thamires
 */
public class ProjetoMatriz extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoMatriz
     */
    
    String[][] tabela = new String[10][3];
    int i = 0, j = 0;
    
    public ProjetoMatriz() {
        initComponents();
        campobrigatorio1.setVisible(false);
        campobrigatorio2.setVisible(false);
        campobrigatorio3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelcadastro = new javax.swing.JPanel();
        lblnome = new javax.swing.JLabel();
        lblcidade = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        txnome = new javax.swing.JTextField();
        txcidade = new javax.swing.JTextField();
        txestado = new javax.swing.JTextField();
        btsalvar = new javax.swing.JButton();
        btsair = new javax.swing.JButton();
        btimprimir = new javax.swing.JButton();
        campobrigatorio1 = new javax.swing.JLabel();
        campobrigatorio2 = new javax.swing.JLabel();
        campobrigatorio3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnome.setText("Nome:");

        lblcidade.setText("Cidade:");

        lblestado.setText("Estado:");

        txnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnomeActionPerformed(evt);
            }
        });

        txcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcidadeActionPerformed(evt);
            }
        });

        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btsair.setText("Sair");
        btsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsairActionPerformed(evt);
            }
        });

        btimprimir.setText("Imprimir");
        btimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btimprimirActionPerformed(evt);
            }
        });

        campobrigatorio1.setForeground(new java.awt.Color(204, 102, 255));
        campobrigatorio1.setText("Esse campo é obrigatório!");

        campobrigatorio2.setForeground(new java.awt.Color(204, 102, 255));
        campobrigatorio2.setText("Esse campo é obrigatório!");

        campobrigatorio3.setForeground(new java.awt.Color(204, 102, 255));
        campobrigatorio3.setText("Esse campo é obrigatório!");

        javax.swing.GroupLayout painelcadastroLayout = new javax.swing.GroupLayout(painelcadastro);
        painelcadastro.setLayout(painelcadastroLayout);
        painelcadastroLayout.setHorizontalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addComponent(lblnome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txnome, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campobrigatorio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                .addComponent(lblestado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txestado, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(campobrigatorio3))
                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                .addComponent(lblcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(campobrigatorio2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelcadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelcadastroLayout.createSequentialGroup()
                        .addComponent(btsalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btimprimir)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelcadastroLayout.createSequentialGroup()
                        .addComponent(btsair, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        painelcadastroLayout.setVerticalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnome)
                    .addComponent(txnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campobrigatorio1))
                .addGap(30, 30, 30)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcidade)
                    .addComponent(txcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campobrigatorio2))
                .addGap(37, 37, 37)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblestado)
                    .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campobrigatorio3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalvar)
                    .addComponent(btimprimir))
                .addGap(9, 9, 9)
                .addComponent(btsair)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcidadeActionPerformed

    private void btsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btsairActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
         
        txnome.requestFocus();
        
        //Ver se todos os campos foram preenchidos
        
        if ((txnome.getText().trim().isEmpty()) || (txcidade.getText().trim().isEmpty()) || (txestado.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Para realizar o cadastro, é necessário que TODOS os campos sejam preenchidos!");
            
            if (txnome.getText().trim().isEmpty()) {
                campobrigatorio1.setVisible(true);
                if (txnome.getText().trim().isEmpty()) { // Coloca o foco se o campo estiver vazio
                txnome.requestFocus();}
                }
            
            else {
            campobrigatorio1.setVisible(false); // Ocultar mensagem se o campo estiver preenchido
             }
            
            if (txcidade.getText().trim().isEmpty()) {
                campobrigatorio2.setVisible(true);
                if (txcidade.getText().trim().isEmpty()) { // Coloca o foco se o campo estiver vazio
                txcidade.requestFocus();
                }
                
            }else {
            campobrigatorio2.setVisible(false); // Ocultar mensagem se o campo estiver preenchido
            }   
            
            if (txestado.getText().trim().isEmpty()) {
                campobrigatorio3.setVisible(true);
                if (txestado.getText().trim().isEmpty()) { // Coloca o foco se o campo estiver vazio
                txestado.requestFocus();
                }
                
            }else {
            campobrigatorio3.setVisible(false); // Ocultar mensagem se o campo estiver preenchido
            }
            
            } 
            else {
            tabela[i][j] = txnome.getText();
            j++;
            tabela[i][j] = txcidade.getText();
            j++;
            tabela[i][j] = txestado.getText();
            j = 0; i++;
            
            //Quando clicar no botão de cadastro
            JOptionPane.showMessageDialog(this, "Os dados foram cadastrados");
            
            //Limpar o painel de cadastro
            txnome.setText(" ");
            txcidade.setText(" ");
            txestado.setText(" ");
            
            //Apagar o campo de mensagens obrigatórias
            
            campobrigatorio1.setVisible(false);
            campobrigatorio2.setVisible(false);
            campobrigatorio3.setVisible(false);

        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void txnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnomeActionPerformed
        JLabel nomeLabel = new JLabel("Nome:");
        nomeLabel.setBounds(10, 10, 80, 25);
        add(nomeLabel);
    }//GEN-LAST:event_txnomeActionPerformed

    private void btimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btimprimirActionPerformed

       //Transformar matriz em string  
       
       String planilha = " ";
         for(i=0 ; i < tabela.length; i++){
             for(j=0 ; j < 3; j++){
                 if (tabela[i][j] == null) {
                planilha += " Campo vazio "; // Substitui "null" por "Campo vazio"
               } else {
                 planilha += tabela[i][j];
                 planilha += " - ";
             }
             }
             planilha += "\n-------------------------------------------------------------------------------------\n";
         }
        JOptionPane.showMessageDialog(null,planilha);
        System.out.println(planilha);
        
    }//GEN-LAST:event_btimprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoMatriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btimprimir;
    private javax.swing.JButton btsair;
    private javax.swing.JButton btsalvar;
    private javax.swing.JLabel campobrigatorio1;
    private javax.swing.JLabel campobrigatorio2;
    private javax.swing.JLabel campobrigatorio3;
    private javax.swing.JLabel lblcidade;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblnome;
    private javax.swing.JPanel painelcadastro;
    private javax.swing.JTextField txcidade;
    private javax.swing.JTextField txestado;
    private javax.swing.JTextField txnome;
    // End of variables declaration//GEN-END:variables
}
